### ISSUE TITLE
seems to be using hard coded local ip

### ISSUE THREAD

**Issue by Luiz-N** [rllola/airbnb-scanner#1]
hi there.. saw this repo from HP alumni slack... i like the idea and managed to get the script running but getting no results.. looking at the code i think this might be due to a hard coded local ip instead of pinging for it dynamically?

at this line of code:

https://github.com/rllola/airbnb-scanner/blob/master/src/application.py#L29

readme could also use some better instructions on how to run the main.py file

**Comment by Luiz-N** [comment]
nevermind i didn't know what i was talking about... apparently that is a way to scan all hosts on a network... I don't get any results in outputted table though

**Comment by rllola** [comment]
Yes 192.168 is a private network (https://en.wikipedia.org/wiki/Private_network). I am not sure about the others networks. Maybe we could also scan them...

I will improve the README thank you for your interest. I have been busy switching from `pyinstaller` to `pyqtdepoy` to create executable because of one issue when using linux (which I use).

The arping method I am using is not full proof. It might be interesting to have several scans and collect all the results. You could also try with another tool (https://en.wikipedia.org/wiki/Arping) and compare result.
